services:
  postgres:
    restart: always
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=short_url'
      - 'POSTGRES_PASSWORD=password_admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network

  short-url-server:
    restart: always
    build: ./ShortUrlServer
    ports:
      - '8761:8761'
    networks:
      - network

  short-url:
    restart: always
    build: ./ShortUrlService
    networks:
      - network
    depends_on:
      - postgres
      - short-url-server

  redis:
    image: redis
    ports:
      - "6379:6379"

  api-gateway:
    restart: always
    build: ./ApiGateway
    ports:
      - '8090:8090'
    networks:
      - network
    depends_on:
      - short-url
      - redis

networks:
  network:
    driver: bridge
