life:
  url:
    minutes: 10

spring:
  application:
    name: ShortUrlService
  datasource:
    url: jdbc:postgresql://postgres:5432/short_url
    username: admin
    password: password_admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

server:
  port: 0
  servlet:
    context-path: /api/v1