spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ShortUrlServiceGenerate
          uri: lb://ShortUrlService
          predicates:
            - Path=/api/v1/generate
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAddressKeyResolver}"
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 100
                redis-rate-limiter.timeout: 1000
        - id: ShortUrlServiceGenerate
          uri: lb://ShortUrlService
          predicates:
            - Path=/api/v1/**

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/