spring:
  application:
    name: ApiGateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ShortUrlServiceGenerate
          uri: lb://ShortUrlService
          predicates:
            - Path=/api/v1/generate
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipAddressKeyResolver}"
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 100
        - id: ShortUrlServiceGenerate
          uri: lb://ShortUrlService
          predicates:
            - Path=/api/v1/**

server:
  port: 8090

eureka:
  client:
    should-unregister-on-shutdown: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
